apiVersion: v1
kind: Service
metadata:
 name: nginx-loadbalancer
 labels:
    app: my-nginx
spec:
 type: ClusterIP
 selector:
    app: my-nginx
 ports:
  - name: "80"
    port: 8080
    targetPort: 8080